name: Build & Deploy Flutter Web

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/flutter-build-web.yml'

# Allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install Dependencies
      working-directory: ./frontend
      run: flutter pub get

    - name: Enable Flutter Web
      run: flutter config --enable-web

    - name: Build Flutter Web
      working-directory: ./frontend
      run: flutter build web --release --base-href "/Aiseekho_hackthon/"

    - name: Upload Web Build Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: frontend/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
